-- --------------------------------------------------------
-- Hôte:                         127.0.0.1
-- Version du serveur:           12.0.2-MariaDB - mariadb.org binary distribution
-- SE du serveur:                Win64
-- HeidiSQL Version:             12.13.0.7147
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Listage de la structure de la base pour sorienter
CREATE DATABASE IF NOT EXISTS `sorienter` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_uca1400_ai_ci */;
USE `sorienter`;

-- Listage de la structure de table sorienter. tbl_connection
CREATE TABLE IF NOT EXISTS `tbl_connection` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `location_a_id` int(11) NOT NULL,
  `location_b_id` int(11) NOT NULL,
  `weight` int(11) NOT NULL,
  `pmr` tinyint(1) NOT NULL,
  `instruction_a_to_b` text DEFAULT NULL,
  `instruction_b_to_a` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `location_a_id` (`location_a_id`),
  KEY `location_b_id` (`location_b_id`),
  CONSTRAINT `tbl_connection_ibfk_1` FOREIGN KEY (`location_a_id`) REFERENCES `tbl_location` (`id`),
  CONSTRAINT `tbl_connection_ibfk_2` FOREIGN KEY (`location_b_id`) REFERENCES `tbl_location` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=172 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

-- Listage des données de la table sorienter.tbl_connection : ~171 rows (environ)
INSERT INTO `tbl_connection` (`id`, `location_a_id`, `location_b_id`, `weight`, `pmr`, `instruction_a_to_b`, `instruction_b_to_a`) VALUES
	(1, 9, 23, 1, 1, 'passer par la porte qui est à droite quand on regarde vers les portes coulissantes, sur la porte il y a un cadre "secretariat"', 'passer par la porte'),
	(2, 9, 2, 1, 1, 'passer par les portes coulissantes et se sera la partie gauche du couloir', 'quand on arrive devant une heure numérique rouge, on peut voir des portes coulissantes, il faut passer par les portes coulissantes'),
	(3, 2, 6, 1, 0, 'si vous voyez une heure numérique rouge, vous devez voir des escaliers derrière', 'si vous voyez une heure numérique rouge, le couloir est derrière et se sera la partie à votre droite'),
	(4, 6, 10, 1, 0, 'en montant une partie des escaliers, il y a une grande porte avec le cadre "salle du mont"', 'passer par la grande porte'),
	(5, 2, 12, 1, 1, 'la salle S7 a une porte avec un cadre "7", si vous êtes au niveau des portes coulissantes se sera la 2ème porte à votre gauche, si vous êtes dans un carrefour se sera la 5ème porte à votre droite', 'passer par la porte'),
	(6, 2, 13, 1, 1, 'la salle S11 a une porte avec un cadre "11", si vous êtes au niveau des portes coulissantes se sera la 3ème porte à votre gauche, si vous êtes dans un carrefour se sera la 4ème porte à votre droite', 'passer par la porte'),
	(7, 2, 14, 1, 1, 'la salle S15 a une porte avec un cadre "15", si vous êtes au niveau des portes coulissantes se sera la 3ème porte à votre gauche, si vous êtes dans un carrefour se sera la 3ème porte à votre droite', 'passer par la porte'),
	(8, 2, 15, 1, 1, 'la salle S19 a une porte avec un cadre "19", si vous êtes au niveau des portes coulissantes se sera la 4ème porte à votre gauche, si vous êtes dans un carrefour se sera la 2ème porte à votre droite', 'passer par la porte'),
	(9, 2, 16, 1, 1, 'le foyer TV a une porte avec un cadre "foyer TV", si vous êtes au niveau des portes coulissantes se sera la 5ème porte à votre gauche, si vous êtes dans un carrefour se sera la 1ère porte à votre droite', 'passer par la porte'),
	(10, 2, 157, 1, 1, 'aller devant les portes coulissantes au milieu du couloir, en regardant les portes coulissantes aller à votre droite jusqu\'à être à un endroit avec plusieurs chemins', 'regarder autour de vous, le couloir principal est le couloir qui est le plus long'),
	(11, 157, 17, 1, 1, 'regarder vers le couloir principal, retournez-vous et se sera la portre de gauche', 'passer par la porte'),
	(12, 157, 22, 1, 1, 'regarder autour de vous jusqu\'à voir des portes rouges, passer par les portes rouge, vous devrez voir des casiers dans la pièce où vous êtes, les 2 portes mènent à la cantine', 'regarder vers les fenêtres ,tournez-vous vers la droite, il devrai y avoir une porte, passer la, normalement vous êtes dans une pièce avec des casiers, passer dans le passage qui est entre les casiers'),
	(13, 157, 1, 1, 1, 'regarder autour de vous jusqu\'à voir un ascenseur gris', 'quand vous sortez de l\'ascenseur, aller dans le passage qui est en face'),
	(14, 157, 8, 1, 0, 'regarder autour de vous jusqu\'à voir l\'ascenseur, aller vers l\'ascenseur, tourner a gauche et normalement vous devriez voir des escaliers', 'regarder la porte qui mène à la cour, tourner a droite, il devrai y avoir un passage'),
	(15, 2, 20, 1, 1, 'la salle immanuel kant est une porte à carreaux vitrés qui a des fenètres à côté, si vous êtes au niveau des portes coulissantes la porte sera à votre droite, si vous êtes dans un carrefour la porte sera à votre gauche', 'passer par la porte à carreaux vitrés'),
	(16, 20, 21, 1, 1, 'à gauche des fauteuils bleu et gris, il devrai y avoir une porte', 'regarder la porte qui mène à la cour, retournez-vous, il devrai y avoir une porte'),
	(17, 2, 19, 1, 1, 'si vous êtes au niveau des portes coulissantes il y aura un mur un peu reculé à votre droite, si vous êtes au niveau du carrefour se sera à votre gauche, il y aura 3 portes et la salle "info autonomie" sera la porte qui est à gauche quand on regarde du couloir', 'passer par la porte'),
	(18, 2, 18, 1, 1, 'le cadre educatif a une porte avec un tape code à côté, si vous êtes au niveau des portes coulissantes se sera la 1ère porte à votre droite, si vous êtes au niveau du carrefour se sera la 3ème porte à votre gauche', 'passer par la porte'),
	(19, 3, 24, 1, 1, 'l\'adjoint de direction a une porte avec un cadre "adjoint de direction", si vous êtes au niveau des portes coulissantes se sera la 1ère porte à votre droite, si vous êtes au niveau du croisement des couloirs se sera la 6ème porte à votre gauche', 'passer par la porte'),
	(20, 3, 25, 1, 1, 'la direction a une porte avec un cadre "direction", si vous êtes au niveau des portes coulissantes se sera la2ème porte à votre droite, si vous êtes au niveau du croisement des couloirs se sera la 5ème porte à votre gauche', 'passer par la porte'),
	(21, 3, 26, 1, 1, 'la salle S10 a une porte avec un cadre "10", si vous êtes au niveau des portes coulissantes se sera la 3ème porte à votre droite, si vous êtes au niveau du croisement des couloirs se sera la 4ème porte à votre gauche', 'passer par la porte'),
	(22, 3, 27, 1, 1, 'la salle S14 a une porte avec un cadre "14", si vous êtes au niveau des portes coulissantes se sera la 4ème porte à votre droite, si vous êtes au niveau du croisement des couloirs se sera la 3ème porte à votre gauche', 'passer par la porte'),
	(23, 3, 28, 1, 1, 'la salle S18 a une porte avec un cadre "18", si vous êtes au niveau des portes coulissantes se sera la 5ème porte à votre droite, si vous êtes au niveau du croisement des couloirs se sera la 2ème porte à votre gauche', 'passer par la porte'),
	(24, 3, 29, 1, 1, 'la salle FC-PRO a une porte  près d\'un extincteur de feu avec un cadre "FC-PRO", si vous êtes au niveau des portes coulissantes se sera la 6ème porte à votre droite, si vous êtes au niveau du croisement des couloirs se sera la 1ère porte à votre gauche', 'passer par la porte'),
	(25, 3, 35, 1, 1, 'si vous êtes au niveau des portes coulissantes il y aura un mur un peu reculé à votre gauche, si vous êtes au niveau du croisement de couloir se sera à votre droite, il y aura 3 portes et la salle S8 sera la porte qui est à gauche quand on regarde du couloir', 'passer par la porte'),
	(26, 3, 36, 1, 1, 'si vous êtes au niveau des portes coulissantes il y aura un mur un peu reculé à votre gauche, si vous êtes au niveau du croisement de couloir se sera à votre droite, il y aura 3 portes et la salle RDV sera la porte qui est au milieu quand on regarde du couloir', 'passer par la porte'),
	(27, 3, 37, 1, 1, 'si vous êtes au niveau des portes coulissantes il y aura un mur un peu reculé à votre gauche, si vous êtes au niveau du croisement de couloir se sera à votre droite, il y aura 3 portes et le foyer baby sera la porte qui est à droite quand on regarde du couloir', 'passer par la porte'),
	(28, 3, 38, 1, 1, 'la porte pour aller aux casiers est un porte vitrés qui est à votre droite si vous êtes au niveau du croisement des couloirs ou à votre gauche si vous êtes au niveau des portes coulissantes', 'en regardant les casiers, regarder à gauche, il devrai y avoir une porte'),
	(29, 38, 39, 1, 1, 'en regardant les casiers, retournez-vous, normalement vous devriez voir une porte vitrée marron', 'regarder du côté des fenêtres, regarder à votre gauche, normalement vous verrez une porte vitrée marron'),
	(30, 2, 3, 1, 1, 'avancer dans le couloir jusqu\'à passer devant des portes coulissantes, quand vous passerez devant vous serez dans le couloir principal droite', 'avancer jusqu\'à passer devant des portes coulissantes, quand vous passerez devant vous serez dans le couloir principal gauche'),
	(31, 3, 122, 1, 1, 'avancer jusqu\'à être dans un croisement de couloir, se sera le couloir en face', 'avancer jusqu\'à être dans un croisement de couloir, se sera le couloir en face'),
	(32, 3, 4, 1, 1, 'avancer jusqu\'à être dans un croisement de couloir, se sera le couloir à votre gauche', 'avancer jusqu\'à être dans un croisement de couloir, se sera le couloir à votre droite'),
	(33, 122, 30, 1, 1, 'mettez-vous au niveau du croisement de couloirs, se sera la 1ère porte à droite', 'passer par la porte'),
	(34, 122, 31, 1, 1, 'mettez-vous au niveau du croisement de couloirs, avancer dans le couloir jusqu\'à la 2ème porte à droite avec le cadre "24 bis"', 'passer par la porte'),
	(35, 122, 32, 1, 1, 'mettez-vous au niveau du croisement de couloirs, avancer dans le couloir jusqu\'à la 3ème porte à droite qui a un cadre "26"', 'passer par la porte'),
	(36, 122, 33, 1, 1, 'mettez-vous au niveau du croisement de couloirs, avancer dans le couloir jusqu\'à la 4ème porte à droite avec un cadre "26 bis"', 'passer par la porte'),
	(37, 122, 34, 1, 1, 'tournez-vous comme si vous venez du croisement de couloirs, se sera la dernière porte à droite', 'passer par la porte'),
	(38, 122, 40, 1, 1, 'mettez-vous au niveau du croisement de couloirs, avancer jusqu\'à voir la porte avec un cadre "espace détente"', 'passer par la porte'),
	(39, 122, 41, 1, 1, 'mettez-vous au niveau du croisement de couloirs, avancer jusqu\'à voir une porte avec un cadre "pôle pro"', 'passer par la porte'),
	(40, 122, 42, 1, 1, 'aller au fond du couloir, se sera la dernière porte à gauche', 'passer par la porte'),
	(41, 4, 7, 1, 0, 'aller au niveau du couloir et avancer un peu et les escaliers seront à droite', 'descendre les escaliers'),
	(42, 4, 43, 1, 1, 'aller devant les escaliers, avancer jusqu\'au toilette, avancer jusqu\'à la prochaine porte', 'passer par la porte'),
	(43, 4, 44, 1, 1, 'aller devant les escaliers, avancer jusqu\'à la 2ème porte qui a le cadre "petit amphi"', 'regarder le tableau, tourner sur votre gauche, passer par la porte'),
	(44, 4, 45, 1, 1, 'aller devant les escaliers, avancer jusqu\'à la 3ème porte avec le cadre "34"', 'passer la porte qui est à droite quand on regarde le tableau'),
	(45, 4, 46, 1, 1, 'la porte de la salle se trouve au fond du couloir, il y a juste à avancer', 'passer par la porte'),
	(46, 2, 11, 1, 1, 'la porte de la vie solaire est celle avec un cadre "bureau vie scolaire" si vous êtes au niveau des portes coulissantes se sera la 1ère porte à gauche, si vous êtes au niveau du carrefour se sera la 6ème porte à droite', 'passer par la porte'),
	(47, 44, 45, 1, 1, 'à droite du tableau, il y a une porte qui mène à la salle S34', 'à gauche du tableau, il y a une porte qui mène à la salle S32'),
	(48, 8, 54, 1, 0, 'monter les escaliers jusqu\'au 1er étage', 'descendre les escaliers jusqu\'au rez de chausée'),
	(49, 7, 53, 1, 0, 'monter les escaliers jusqu\'au 1er étage', 'descendre les escaliers'),
	(50, 6, 52, 1, 0, 'monter les escaliers jusqu\'au 1er étage', 'descendre les escaliers'),
	(51, 1, 47, 1, 1, 'aller au 1er étage', 'aller au rez de chausée'),
	(52, 53, 50, 1, 0, 'normalement vous êtes dans un couloir et près de l\'escalier qui monte un cadre avec des infos sur le 1er étage', 'mettez-vous au niveau du carrefour, avancer un peu et il y aura les escaliers à droite'),
	(53, 54, 158, 1, 0, 'normalement vous êtes à un endroit avec 2 passages', 'si vous aller au bout du couloir principal du 1er étage devant l\'infirmerie, mettez vous fasse a la porte et aller à droite, il y aura les escaliers sur votre gauche'),
	(54, 52, 48, 1, 0, 'normalement vous êtes dans un couloir avec une grande porte en face et quand vous regardez sur les côtés il y a des grandes portes aussi', 'aller devant la grande porte au milieu du couloir, si vous regardez la grande porte les escaliers sont derrière vous'),
	(55, 158, 66, 1, 1, 'si vous regarder les escaliers, à droite il y a un couloir, aller dans le couloir et le labo SVT sera à gauche', 'passer par la porte'),
	(56, 158, 67, 1, 1, 'si vous regarder les escaliers, aller à droite et aller au fond du couloir', 'passer par la porte'),
	(57, 158, 48, 1, 1, 'si vous regarder les escaliers, aller à gauche', 'mettez vous face a la porte de l\'infirmerie, c\'est à droite'),
	(58, 47, 158, 1, 1, 'sortez de l\'ascenceur', 'si vous regardez les escaliers, tourner à droite, il devrai y avoir un couloir et à côté du couloir l\'ascenseur'),
	(59, 48, 65, 1, 1, 'aller à l\'escalier principal, en regardant l\'escalier aller à votre gauche et la porte de l\'infirmerie sera au fond, si vous êtes au niveau du carrefour se sera juste à droite quand vous aller dans le couloir principal', 'passer par la porte'),
	(60, 48, 55, 1, 1, 'aller à l\'escalier principal au mileu du couloir, regarder l\'escalier et la salle 100 sera derrière vous, si vous êtes au niveau du carrefour avancer jusqu\'au escaliers', 'passer par la porte'),
	(61, 48, 56, 1, 1, 'aller à l\'escalier principal au milieu du couloir, en regarder l\'escalier et aller à votre gauche, se sera la 1ère porte avec un cadre "comptabilité", si vous êtes au niveau du carrefour se sera la 9ème porte', 'passer par la porte'),
	(62, 48, 57, 1, 1, 'aller à l\'escalier principal au milieu du couloir, en regardant l\'escalier aller à votre gauche, se sera la 2ème porte avec un cadre avec le numéro "103", si vous êtes au niveau du carrefour c\'est la 8ème porte', 'passer par la porte'),
	(63, 48, 58, 1, 1, 'aller à l\'escalier principal au milieu du couloir, en regardant l\'escalier aller à votre gauche jusqu\'à la 3ème porte avec un cadre qui a le numéro "105", si vous êtes au niveau du carrefour c\'est la 7ème porte', 'passer par la porte'),
	(64, 48, 59, 1, 1, 'aller à l\'escalier principal au milieu du couloir, en regardant l\'escalier aller à votre gauche jusqu\'à la 4ème porte avec un cadre "coordinateur pédagogique", si vous êtes au niveau du carrefour c\'est 6ème porte', 'passer par la porte'),
	(65, 48, 60, 1, 1, 'aller à l\'escalier principal au milieu du couloir, en regardant l\'escalier aller à votre gauche jusqu\'à la 5ème porte avec un cadre qui a le numéro "111", si vous êtes au niveau du carrefour c\'est la 5ème porte', 'passer par la porte'),
	(66, 48, 61, 1, 1, 'aller à l\'escalier principal au milieu du couloir, en regardant l\'escalier aller à gauche jusqu\'à la 6ème porte avec un cadre qui a le numéro "115", si vous êtes au niveau du carrefour c\'est la 4ème porte', 'passer par la porte'),
	(67, 48, 62, 1, 1, 'aller à l\'escalier principal au milieu du couloir, en regardant l\'escalier aller sur votre gauche jusqu\'à la 7ème porte avec le cadre "119", si vous êtes au niveau du carrefour c\'est la 3ème porte', 'passer par la porte'),
	(68, 48, 63, 1, 1, 'aller à l\'escalier principal au milieu du couloir, en regardant l\'escalier aller à votre gauche jusqu\'à la 8ème porte avec le cadre "121", si vous êtes au niveau du carrefour c\'est la 2ème porte', 'passer par la porte'),
	(69, 48, 64, 1, 1, 'aller à l\'escalier principal au milieu du couloir, en regardant l\'escalier aller à votre gauche jusqu\'à la 9ème porte avec un cadre qui a le numéro "123", si vous êtes au niveau du carrefour c\'est la 1ère porte', 'passer par la porte'),
	(70, 49, 68, 1, 1, 'aller à l\'escalier principal au milieu du couloir, en regardant l\'escalier aller à votre droite jusqu\'à voir la porte avec le cadre "salle des profs", sa devrai être la 1ère porte, si vous êtes au niveau du croisement de couloirs c\'est la 7ème porte sans compter la salle S124', 'passer par la porte'),
	(71, 49, 69, 1, 1, 'aller à l\'escalier principal au milieu du couloir, en regardant l\'escalier aller à votre droite jusqu\'à la 2ème porte avec le cadre "responsable informatique", si vous êtes au niveau du croisement de couloirs c\'est la 6ème porte sans compter la salle S124', 'passer par la porte'),
	(72, 49, 70, 1, 1, 'aller à l\'escalier principal au milieu du couloir, en regardant l\'escalier aller à votre droite jusqu\'à la 3ème porte avec le cadre "coordinateur pédagogique", si vous êtes au niveau du croisement de couloir c\'est la 5ème porte sans compter la salle S124', 'passer par la porte'),
	(73, 49, 71, 1, 1, 'aller à l\'escalier principal au milieu du couloir, en regardant l\'escalier aller à votre droite jusqu\'à la 4ème porte qui a le cadre avec le numéro "112", si vous êtes au niveau du croisement de couloirs c\'est la 4ème porte sans compter la salle S124', 'passer par la porte'),
	(74, 49, 72, 1, 1, 'aller à l\'escalier principal au milieu du couloir, en regardant l\'escalier aller à votre droite jusqu\'à la 5ème porte qui a le cadre avec le numéro "114", si vous êtes au niveau du croisement de couloirs c\'est la 3ème porte sans compter la salle S124', 'passer par la porte'),
	(75, 49, 73, 1, 1, 'aller à l\'escalier principal au milieu du couloir, en regardant l\'escalier aller à votre droite jusqu\'à la 6ème porte avec le cadre qui a le numéro "118", si vous êtes au niveau du croisement de couloirs c\'est la 2ème porte sans compter la salle S124', 'passer par la porte'),
	(76, 72, 73, 1, 1, 'regarder le tableau et retournez-vous derrière, la porte sera au fond de la salle et mène à la salle S118', 'la porte est à droite du tableau et mène à la salle S114'),
	(77, 49, 74, 1, 1, 'aller à l\'escalier principal au milieu du couloir, en regardant l\'escalier aller à votre droite jusqu\'à voir une porte avec le cadre qui a le numéro "122", la porte est entre 2 extincteurs de feu, si vous êtes au niveau du croisement de couloirs c\'est la 1ère porte sans compter la salle S124', 'passer par la porte'),
	(78, 49, 50, 1, 1, 'aller au croisement de couloirs, se sera le couloir qui est à votre gauche', 'regarder la salle S124, le couloir principal droite est à votre droite'),
	(79, 50, 75, 1, 1, 'regarder autour de vous et vous verrez la porte avec le cadre "124"', 'passer par la porte'),
	(80, 49, 162, 1, 1, 'aller au croisement de couloirs, c\'est le couloir d\'en face', 'aller au croisement de couloirs, c\'est le couloir d\'en face'),
	(81, 162, 160, 1, 1, 'aller au niveau du croisement de couloirs, avancer un peu et se sera la 1ère salle à votre droite', 'passer par la porte'),
	(82, 162, 76, 1, 1, 'aller au niveau du croisement de couloirs et avancer jusqu\'à la 2ème porte à droite avec le cadre "126 bis"', 'passer par la porte'),
	(83, 160, 76, 1, 1, 'regarder le tableau et retournez-vous, la porte est au fond de la salle et mène à la salle S126 bis', 'la porte qui mène à la salle S126 est à gauche du tableau'),
	(84, 162, 77, 1, 1, 'aller au niveau du croisement de couloirs et avancer jusqu\'à la 3ème porte à droite avec le cadre "126 ter"', 'passer par la porte'),
	(85, 50, 78, 1, 1, 'aller au niveau du croisement de couloirs, avancer un peu et se sera la 1ère porte à votre gauche', 'passer par la porte'),
	(86, 162, 50, 1, 1, 'aller au croisement de couloirs et se sera le couloir à votre droite', 'aller au croisement de couloirs et se sera le couloir à votre gauche'),
	(87, 50, 80, 1, 1, 'regarder les escaliers et aller à votre gauche, se sera la porte qui est à côté des toilettes', 'passer par la porte'),
	(88, 50, 81, 1, 1, 'regarder les escaliers et aller à votre gauche jusqu\'à voir un mur un peu reculé à droite, il y aura la porte avec le cadre "132"', 'passer par la porte'),
	(89, 50, 82, 1, 1, 'regarder les escaliers et aller à votre gauche jusqu\'à la porte qui est au fond et entrer dans la salle', 'passer par la porte'),
	(90, 82, 83, 1, 1, 'la porte qui mène à la salle S138 est à côté de l\'ordi du prof', 'la porte qui mène à la salle S136 est à droite du tableau'),
	(91, 53, 79, 1, 1, 'monter les escaliers sans aller à l\'étage superieur, il y aura une porte entre les 2 parties de l\'escalier', 'passer par la porte'),
	(92, 162, 123, 1, 1, 'aller au fond du couloir, il y aura une porte avec des escaliers derrière, monter les escaliers et vous serez à la salle "S242"', 'passer par la porte'),
	(93, 47, 92, 1, 1, 'monter dans l\'ascenseur et choisissez l\'étage 2', 'monter dans l\'asccenseur et choisissez l\'étage 1'),
	(94, 52, 96, 1, 0, 'monter les escaliers de l\'étage 1 pour aller à l\'étage 2', 'descendre les escaliers de l\'étage 2 pour aller à l\'étage 1'),
	(95, 53, 97, 1, 0, 'monter les escaliers de l\'étage 1 pour aller à l\'étage 2', 'descendre les escaliers de l\'étage 2 pour aller à l\'étage 1'),
	(96, 54, 98, 1, 0, 'monter les escaliers de l\'étage 1 pour aller à l\'étage 2', 'descendre les escaliers de l\'étage 2 pour aller à l\'étage 1'),
	(97, 9, 3, 1, 1, 'passer par les portes coulissantes, se sera vers votre droite', 'quand vous serez devant une heure numérique rouge, se sera les portes coulissantes qui seront à votre gauche'),
	(98, 3, 6, 1, 0, 'avancez jusqu\'à voir une heure numérique rouge, les escaliers seront derrière', 'quand vous descendez les escaliers il y aura une heure numérique rouge, se sera le couloir derrière et il faut aller vers votre gauche'),
	(99, 4, 122, 1, 1, 'quand vous arrivez à un croisement de couloir, aller dans le couloir à votre gauche', 'quand vous arrivez à un croisement de couloir, aller dans le couloir à votre droite'),
	(100, 52, 49, 1, 0, 'aller dans le couloir à votre gauche', 'avancer jusqu\'à voir des escaliers à votre droite'),
	(101, 49, 55, 1, 1, 'avancer jusqu\'à l\'escalier qui sera à votre droite, à votre gauche il y aura une grande porte qui est la salle S100', 'passer par la porte'),
	(102, 49, 75, 1, 1, 'quand vous êtes au croisement de couloir, se sera la salle qui est en face du couloir qui est à votre gauche', 'passer la porte et c\'est le couloir à votre gauche'),
	(103, 162, 75, 1, 1, 'aller au croisement de couloir et se sera la porte à votre gauche', 'passer la porte et se sera le couloir à votre droite'),
	(104, 48, 49, 1, 1, 'avancer jusqu\'à escalier principal, quand vous passerez devant vous serez dans le couloir principal droite', 'avancer jusqu\'à l\'escalier principal, quand vous passerez devant vous serez dans le couloir princiapl gauche'),
	(105, 96, 94, 1, 0, 'après avoir monter les escaliers, il faut aller dans la partie du couloir à votre gauche', 'si vous êtes au niveau du couloir secondaire, aller vers le milieu du couloir principal, se sera l\'escalier à votre droite'),
	(106, 96, 93, 1, 0, 'après avoir monter les escaliers, il faut aller dans la partie à votre droite', 'aller vers le milieu du couloir, se sera les escaliers à votre gauche'),
	(107, 94, 93, 1, 1, 'avancer jusqu\'à l\'escalier principal, après être passer devant vous serez dans la partie gauche du couloir principal', 'avancer jusqu\'à l\'escalier principal, après être passer devant vous serez dans la partie droite du couloir principal'),
	(108, 97, 163, 1, 0, 'après avoir monter les escaliers vous serez dans le couloir secondaire', 'si vous êtes au niveau du couloir principal droite les escaliers seront sur votre droite, si vous êtes au niveau d\'une salle les escaliers seront sur votre gauche'),
	(109, 94, 163, 1, 1, 'aller au bout du couloir et le couloir secondaire sera à voter gauche', 'aller au bout du couloir à votre droite quand on regarde les escaliers, se sera le couloir à votre droite'),
	(110, 98, 113, 1, 0, 'après avoir monter les escaliers, l\'internat sera à votre gauche', 'les escaliers seront à votre droite quand vous sortez de l\'internat'),
	(111, 92, 113, 1, 1, 'quand vous sortez de l\'ascenseur l\'internat sera à votre droite', 'l\'ascenseur sera à votre gauche quand vous sortez de l\'internat'),
	(112, 94, 99, 1, 1, 'si vous êtes au niveau des escaliers c\'est la porte en face, si vous êtes au bout du couloir aller vers le mileu du couloir principal, il aura des escaliers à votre droite et la salle S200 sera à votre gauche', 'le couloir principal droite sera à votre droite'),
	(113, 93, 99, 1, 1, 'si vous êtes au niveau des escaliers c\'est la porte en face, si vous êtes au bout du couloir aller vers le milieu du couloir principal, il y aura des escaliers à votre gauche et la salle S200 sera à votre droite', 'le couloir principal gauche sera à votre gauche'),
	(114, 93, 100, 1, 1, 'si vous êtes au niveau des escaliers se sera la 2ème porte, si vous êtes au croisement de couloirs se sera la 10ème porte', 'passer par la porte'),
	(115, 93, 101, 1, 1, 'si vous êtes au niveau des escaliers se sera la 3ème porte, si vous êtes au niveau du croisement de couloirs se sera la 9ème porte', 'passer par la porte'),
	(116, 93, 102, 1, 1, 'si vous êtes au niveau des escaliers se sera la 4ème porte, si vous êtes au niveau du croisement de couloirs se sera la 8ème porte', 'passer par la porte'),
	(117, 93, 103, 1, 1, 'si vous êtes au niveau des escaliers se sera la 5ème porte, si vous êtes au niveau du croisement de couloirs se sera la 7ème porte', 'passer par la porte'),
	(118, 93, 104, 1, 1, 'si vous êtes au niveau des escaliers se sera la 6ème porte, si vous êtes au niveau du croisement de couloirs se sera la 6ème porte', 'passer par la porte'),
	(119, 93, 105, 1, 1, 'si vous êtes au niveau des escaliers se sera la 7ème porte, si vous êtes au niveau du croisement de couloirs se sera la 5ème porte', 'passer par la porte'),
	(120, 93, 106, 1, 1, 'si vous êtes au niveau des escaliers se sera la 8ème porte, si vous êtes au niveau du croisement de couloir se sera la 4ème porte', 'passer par la porte'),
	(121, 93, 107, 1, 1, 'si vous êtes au niveau des escaliers se sera la 9ème porte, si vous êtes au niveau du croisement de couloirs se sera la 3ème porte', 'passer par la porte'),
	(122, 93, 108, 1, 1, 'si vous êtes au niveau des escaliers se sera la 10ème porte, si vous êtes au niveau du croisement de couloir se sera la 2ème porte', 'passer par la porte'),
	(123, 93, 109, 1, 1, 'si vous êtes au niveau des escaliers se sera la 11ème porte, si vous êtes au croisement de couloirs se sera la 1ère porte', 'passer par la porte'),
	(124, 93, 110, 1, 1, 'aller au croisement de couloir, ensuite aller au couloir à votre gauche et se sera la salle au bout du couloir', 'passer par la porte'),
	(125, 93, 111, 1, 1, 'aller au croisement de couloir, ensuite aller au couloir à votre gauche et se sera la 2ème porte', 'passer par la porte'),
	(126, 93, 112, 1, 1, 'aller au croisement de couloir, ensuite aller au couloir à votre gauche et se sera la 1ère porte', 'passer par la porte'),
	(127, 94, 114, 1, 1, 'si vous êtes au niveau des l\'escaliers se sera la 3ème porte, si vous êtes au niveau du croisement de couloirs c\'est la 6ème porte', 'passer par la porte'),
	(128, 94, 115, 1, 1, 'si vous êtes au niveau des escaliers se sera la 4ème porte, si vous êtes au niveau du croisements de couloirs se sera la 5ème portre', 'passer par la porte'),
	(129, 94, 116, 1, 1, 'si vous êtes au niveau des escaliers se sera la 5ème porte, si vous êtes au niveau du croisement de couloirs se sera la 4ème porte', 'passer par la porte'),
	(130, 94, 117, 1, 1, 'si vous êtes au niveau des escaliers se sera la 6ème porte, si vous êtes au niveau du croisement de couloirs se sera la 3ème porte', 'passer par la porte'),
	(131, 94, 118, 1, 1, 'si vous êtes au niveau des escaliers se sera la 7ème porte, si vous êtes au niveau du croisement de couloirs se sera la 2ème porte', 'passer par la porte'),
	(132, 94, 119, 1, 1, 'si vous êtes au niveau des escaliers se sera la 8ème porte, si vous êtes au niveau du croisement de couloirs se sera la 1ère porte', 'passer par la porte'),
	(133, 94, 120, 1, 1, 'la porte de la salle LV est au croisement des couloirs', 'passer par la porte'),
	(134, 94, 121, 1, 1, 'aller au croisement de couloir, se sera la porte de gauche', 'passer par la porte'),
	(135, 163, 124, 1, 1, 'si vous êtes au niveau des escaliers aller à votre droite et se sera la 1ère porte', 'passer par la porte'),
	(136, 163, 125, 1, 1, 'si vous êtes au niveau des escaliers aller à votre droite et se sera la 2ème porte', 'passer par la porte'),
	(137, 163, 126, 1, 1, 'si vous êtes au niveau des escaliers aller à votre droite et se sera la 3ème porte', 'passer par la porte'),
	(138, 163, 127, 1, 1, 'si vous êtes au niveau des escaliers aller à votre droite et se sera la dernière porte', 'passer par la porte'),
	(139, 92, 128, 1, 1, 'prendre l\'ascenseur et aller à l\'étage 3', 'prendre l\'ascenseur et aller à l\'étage 2'),
	(140, 96, 132, 1, 0, NULL, NULL),
	(141, 97, 133, 1, 0, NULL, NULL),
	(142, 98, 134, 1, 0, NULL, NULL),
	(143, 132, 161, 1, 0, NULL, NULL),
	(144, 132, 129, 1, 0, NULL, NULL),
	(145, 161, 129, 1, 1, NULL, NULL),
	(146, 133, 130, 1, 0, NULL, NULL),
	(147, 130, 156, 1, 1, NULL, NULL),
	(148, 161, 130, 1, 1, NULL, NULL),
	(149, 129, 146, 1, 1, NULL, NULL),
	(150, 135, 161, 1, 1, NULL, NULL),
	(151, 135, 129, 1, 1, NULL, NULL),
	(152, 129, 136, 1, 1, NULL, NULL),
	(153, 129, 137, 1, 1, NULL, NULL),
	(154, 129, 138, 1, 1, NULL, NULL),
	(155, 129, 139, 1, 1, NULL, NULL),
	(156, 129, 140, 1, 1, NULL, NULL),
	(157, 129, 141, 1, 1, NULL, NULL),
	(158, 129, 142, 1, 1, NULL, NULL),
	(159, 129, 143, 1, 1, NULL, NULL),
	(160, 129, 144, 1, 1, NULL, NULL),
	(161, 129, 145, 1, 1, NULL, NULL),
	(162, 161, 95, 1, 1, NULL, NULL),
	(163, 161, 147, 1, 1, NULL, NULL),
	(164, 161, 148, 1, 1, NULL, NULL),
	(165, 161, 149, 1, 1, NULL, NULL),
	(166, 161, 150, 1, 1, NULL, NULL),
	(167, 161, 151, 1, 1, NULL, NULL),
	(168, 161, 152, 1, 1, NULL, NULL),
	(169, 161, 153, 1, 1, NULL, NULL),
	(170, 161, 154, 1, 1, NULL, NULL),
	(171, 161, 155, 1, 1, NULL, NULL);

-- Listage de la structure de table sorienter. tbl_location
CREATE TABLE IF NOT EXISTS `tbl_location` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `floor` int(11) NOT NULL,
  `type` varchar(50) NOT NULL,
  `reference` varchar(255) DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=164 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

-- Listage des données de la table sorienter.tbl_location : ~163 rows (environ)
INSERT INTO `tbl_location` (`id`, `name`, `floor`, `type`, `reference`, `image`) VALUES
	(1, 'asc_RDC', 0, 'ascenseur', NULL, 'asc_RDC.jpg'),
	(2, 'couloir principal gauche', 0, 'couloir', 'carrefour gauche - portes coulissantes', 'couloirPrincG_RDC.jpg'),
	(3, 'couloir principal droite', 0, 'couloir', 'portes coulissantes - croisement de couloirs', 'couloirPrincD_RDC.jpg'),
	(4, 'couloir secondaire', 0, 'couloir', NULL, 'couloirSecon_RDC.jpg'),
	(5, 'carrefour droite', 0, 'couloir', 'croisement de couloirs', NULL),
	(6, 'escaliers principal', 0, 'escaliers', 'heure numérique rouge', 'escPrinc_RDC.jpg'),
	(7, 'escaliers droite', 0, 'escaliers', NULL, 'escD_RDC.jpg'),
	(8, 'escaliers gauche', 0, 'escaliers', 'peut aller à l\'étage supérieur et inférieur', 'escG_RDC.jpg'),
	(9, 'accueil', 0, 'salle', 'portes coulissantes', 'porteCouliAccueil.jpg'),
	(10, 'salle du mont', 0, 'salle', 'grande porte au niveau de l\'escalier principal', NULL),
	(11, 'vie scolaire', 0, 'salle', 'cadre "bureau vie scolaire"', NULL),
	(12, 'casiers 7', 0, 'salle', 'cadre "7"', NULL),
	(13, 'S11', 0, 'salle', 'cadre "11"', 'S11.jpg'),
	(14, 'S15', 0, 'salle', 'cadre "15"', 'S15.jpg'),
	(15, 'S19', 0, 'salle', 'cadre "19"', 'S19.jpg'),
	(16, 'foyer TV', 0, 'salle', 'porte vitré', 'foyer_TV.jpg'),
	(17, 'foyer billiards', 0, 'salle', 'carrefour gauche', NULL),
	(18, 'cadre éducatif', 0, 'salle', 'porte avec un tape code', NULL),
	(19, 'info autonomie', 0, 'salle', 'mur reculé', NULL),
	(20, 'salle immanuel kant', 0, 'salle', 'grande porte à carreaux vitrés', 'SalleImmaKant.jpg'),
	(21, 'foyer 1', 0, 'salle', 'porte dans la salle immanuel kant', NULL),
	(22, 'cantine', 0, 'salle', 'grande porte rouge', NULL),
	(23, 'secretariat', 0, 'salle', 'cadre "secretariat"', NULL),
	(24, 'adjoint de direction', 0, 'salle', 'cadre "adjoint de direction"', 'adjDirection.jpg'),
	(25, 'direction', 0, 'salle', 'cadre "direction"', 'direction.jpg'),
	(26, 'S10', 0, 'salle', 'cadre "10"', 'S10.jpg'),
	(27, 'S14', 0, 'salle', 'cadre "14"', 'S14.jpg'),
	(28, 'S18', 0, 'salle', 'cadre "18"', 'S18.jpg'),
	(29, 'FC-PRO', 0, 'salle', 'à côté d\'un extincteur de feu', 'FC-PRO.jpg'),
	(30, 'S24', 0, 'salle', 'cadre "24"', 'S24.jpg'),
	(31, 'S24 bis', 0, 'salle', NULL, NULL),
	(32, 'S26', 0, 'salle', 'cadre "26"', 'S26.jpg'),
	(33, 'S26 bis', 0, 'salle', NULL, 'S26bis.jpg'),
	(34, 'foyer BTS', 0, 'salle', 'cadre "foyer BTS"', NULL),
	(35, 'S8', 0, 'salle', 'mur reculé', NULL),
	(36, 'salle RDV', 0, 'salle', 'mur reculé', NULL),
	(37, 'foyer 12', 0, 'salle', 'cadre "foyer babyfoot"', NULL),
	(38, 'casiers', 0, 'salle', 'porte vitrée à carreaux', NULL),
	(39, 'médiathèque', 0, 'salle', 'porte marron dans la salle des casiers', 'médiathèque.jpg'),
	(40, 'espace détente', 0, 'salle', NULL, 'espCasiersDetente.jpg'),
	(41, 'pôle pro', 0, 'salle', NULL, NULL),
	(42, 'espace casiers', 0, 'salle', NULL, 'espCasiers.jpg'),
	(43, 'S30', 0, 'salle', 'cadre "30"', 'S30.jpg'),
	(44, 'S32', 0, 'salle', 'cadre "petit amphi"', NULL),
	(45, 'S34', 0, 'salle', 'cadre "34"', 'S34.jpg'),
	(46, 'S36', 0, 'salle', 'porte au fond du couloir secondaire', 'S36.jpg'),
	(47, 'ascenseur étage 1', 1, 'ascenseur', NULL, 'asc_E1.jpg'),
	(48, 'couloir principal gauche étage 1', 1, 'couloir', 'grandes portes marrons', 'couloirPrincG_E1.jpg'),
	(49, 'couloir principal droite étage 1', 1, 'couloir', NULL, 'couloirPrincD_E1.jpg'),
	(50, 'couloir secondaire étage 1', 1, 'couloir', NULL, 'couloirSecon_E1.jpg'),
	(51, 'carrefour droite étage 1', 1, 'couloir', 'croisement de couloirs', NULL),
	(52, 'escaliers principal étage 1', 1, 'escaliers', '2 escaliers vont à l\'étage inférieur', 'escPrinc_E1.jpg'),
	(53, 'escaliers droite étage 1', 1, 'escaliers', NULL, 'escD_E1.jpg'),
	(54, 'escaliers gauche étage 1', 1, 'escaliers', NULL, 'escG_E1.jpg'),
	(55, 'S100', 1, 'salle', 'grande porte au niveau de l\'escalier principal', NULL),
	(56, 'comptabilité', 1, 'salle', 'cadre "comptabilité"', 'comptabilite.jpg'),
	(57, 'S103', 1, 'salle', 'cadre "103"', NULL),
	(58, 'S105', 1, 'salle', 'cadre "105"', NULL),
	(59, 'coordinateur pédagogique 107', 1, 'salle', 'cadre "coordinateur pédagogique"', NULL),
	(60, 'S111', 1, 'salle', 'cadre "111"', NULL),
	(61, 'S115', 1, 'salle', 'cadre "115"', NULL),
	(62, 'S119', 1, 'salle', 'cadre "119"', 'S119.jpg'),
	(63, 'S121', 1, 'salle', 'cadre "121"', NULL),
	(64, 'S123', 1, 'salle', 'cadre "123"', 'S123.jpg'),
	(65, 'infirmerie', 1, 'salle', 'porte au fond du couloir principal du cote gauche', 'infirmerie.jpg'),
	(66, 'labo SVT', 1, 'salle', 'couloir gauche', 'laboSVT_E1.jpg'),
	(67, 'salle tombelaine', 1, 'salle', 'porte au fond du couloir gauche', 'salleTombelaine.jpg'),
	(68, 'salle des profs', 1, 'salle', 'cadre "salle des profs"', 'salleProfs.jpg'),
	(69, 'responsable informatique', 1, 'salle', 'cadre "responsable informatique"', 'respInfo.jpg'),
	(70, 'coordinateur pédagogique 108', 1, 'salle', 'cadre "coordinateur pédagogique"', NULL),
	(71, 'salle des profs ( info )', 1, 'salle', NULL, 'salleTravailProfs.jpg'),
	(72, 'S114', 1, 'salle', 'cadre "114"', 'S114.jpg'),
	(73, 'S118', 1, 'salle', 'cadre "118"', 'S118.jpg'),
	(74, 'serveur', 1, 'salle', 'porte entre des extincteurs de feu', NULL),
	(75, 'S124', 1, 'salle', 'porte dans le carrefour', 'S124.jpg'),
	(76, 'S126 bis', 1, 'salle', NULL, NULL),
	(77, 'S126 ter', 1, 'salle', NULL, NULL),
	(78, 'salle de la baie', 1, 'salle', 'cadre "salle de la baie"', NULL),
	(79, 'S240', 2, 'salle', 'escaliers de droite', NULL),
	(80, 'S130', 1, 'salle', NULL, 'S130.jpg'),
	(81, 'S132', 1, 'salle', 'cadre "S132"', 'S132.jpg'),
	(82, 'S136', 1, 'salle', 'grande porte au fond du couloir secondaire', 'S136.jpg'),
	(83, 'S138', 1, 'salle', 'ordi du prof', 'S138.jpg'),
	(84, 'ascenseur étage -1', -1, 'ascenseur', NULL, NULL),
	(85, 'couloir étage -1', -1, 'couloir', NULL, NULL),
	(86, 'laboratoire physique', -1, 'salle', NULL, NULL),
	(87, 'laboratoire SVT', -1, 'salle', NULL, NULL),
	(88, 'S021', -1, 'salle', NULL, NULL),
	(89, 'S019', -1, 'salle', NULL, NULL),
	(90, 'techno', -1, 'salle', NULL, NULL),
	(91, 'MPI', -1, 'salle', NULL, NULL),
	(92, 'ascenseur étage 2', 2, 'ascenseur', NULL, NULL),
	(93, 'couloir principal gauche étage 2', 2, 'couloir', NULL, NULL),
	(94, 'couloir principal droite étage 2', 2, 'couloir', NULL, NULL),
	(95, 'S350', 3, 'salle', NULL, NULL),
	(96, 'escaliers principal étage 2', 2, 'escaliers', NULL, NULL),
	(97, 'escaliers droite étage 2', 2, 'escaliers', NULL, NULL),
	(98, 'escaliers gauche étage 2', 2, 'escaliers', NULL, NULL),
	(99, 'S200', 2, 'salle', 'porte en face de l\'escalier principal', NULL),
	(100, 'S203', 2, 'salle', NULL, NULL),
	(101, 'S205', 2, 'salle', NULL, NULL),
	(102, 'S207', 2, 'salle', NULL, NULL),
	(103, 'S209', 2, 'salle', NULL, NULL),
	(104, 'S211', 2, 'salle', NULL, NULL),
	(105, 'S213', 2, 'salle', NULL, NULL),
	(106, 'S215', 2, 'salle', NULL, NULL),
	(107, 'S217', 2, 'salle', NULL, NULL),
	(108, 'S219', 2, 'salle', NULL, NULL),
	(109, 'S221', 2, 'salle', NULL, NULL),
	(110, 'S223 TC', 2, 'salle', NULL, NULL),
	(111, 'S225', 2, 'salle', NULL, NULL),
	(112, 'S227', 2, 'salle', NULL, NULL),
	(113, 'internat filles', 2, 'salle', NULL, NULL),
	(114, 'S206', 2, 'salle', NULL, NULL),
	(115, 'S208', 2, 'salle', NULL, NULL),
	(116, 'DISFA 212', 2, 'salle', NULL, NULL),
	(117, 'DISFA 216', 2, 'salle', NULL, NULL),
	(118, 'S220', 2, 'salle', NULL, NULL),
	(119, 'S222', 2, 'salle', NULL, NULL),
	(120, 'salle LV', 2, 'salle', NULL, NULL),
	(121, 'S223', 2, 'salle', NULL, NULL),
	(122, 'couloir secondaire droite', 0, 'couloir', NULL, 'couloirSeconD_RDC.jpg'),
	(123, 'S242', 2, 'salle', NULL, 'S242.jpg'),
	(124, 'S230', 2, 'salle', NULL, NULL),
	(125, 'S232', 2, 'salle', NULL, NULL),
	(126, 'S234', 2, 'salle', NULL, NULL),
	(127, 'S236', 2, 'salle', NULL, NULL),
	(128, 'ascenseur étage 3', 3, 'ascenseur', NULL, NULL),
	(129, 'couloir principal gauche étage 3', 3, 'couloir', NULL, NULL),
	(130, 'couloir secondaire étage 3', 3, 'couloir', NULL, NULL),
	(131, 'carrefour étage 3', 3, 'couloir', 'croisement de couloirs', NULL),
	(132, 'escaliers principal étage 3', 3, 'escaliers', NULL, NULL),
	(133, 'escaliers droite étage 3', 3, 'escaliers', NULL, NULL),
	(134, 'escaliers gauche étage 3', 3, 'escaliers', NULL, NULL),
	(135, 'S300', 3, 'salle', NULL, NULL),
	(136, 'S303', 3, 'salle', NULL, NULL),
	(137, 'S305', 3, 'salle', NULL, NULL),
	(138, 'S307', 3, 'salle', NULL, NULL),
	(139, 'S311', 3, 'salle', NULL, NULL),
	(140, 'S315', 3, 'salle', NULL, NULL),
	(141, 'S319', 3, 'salle', NULL, NULL),
	(142, 'S321', 3, 'salle', NULL, NULL),
	(143, 'foyer internat', 3, 'salle', NULL, NULL),
	(144, 'S327', 3, 'salle', NULL, NULL),
	(145, 'S351', 3, 'salle', NULL, NULL),
	(146, 'internat garçons', 3, 'salle', NULL, NULL),
	(147, 'S302', 3, 'salle', NULL, NULL),
	(148, 'S302 bis', 3, 'salle', NULL, NULL),
	(149, 'S304', 3, 'salle', NULL, NULL),
	(150, 'S306', 3, 'salle', NULL, NULL),
	(151, 'S312', 3, 'salle', NULL, NULL),
	(152, 'S316', 3, 'salle', NULL, NULL),
	(153, 'S318', 3, 'salle', NULL, NULL),
	(154, 'S322', 3, 'salle', NULL, NULL),
	(155, 'S324', 3, 'salle', NULL, NULL),
	(156, 'salle chausey', 3, 'salle', 'grande porte au fond du couloir secondaire', NULL),
	(157, 'partie gauche', 0, 'couloir', 'croisement de couloirs', 'partieG_RDC.jpg'),
	(158, 'partie gauche étage 1', 1, 'couloir', 'croisement de couloirs', 'partieG_E1.jpg'),
	(159, 'escaliers étage -1', -1, 'escaliers', NULL, NULL),
	(160, 'S126', 1, 'salle', 'image d\'informatique sur la porte', NULL),
	(161, 'couloir principal droite étage 3', 3, 'couloir', NULL, NULL),
	(162, 'couloir secondaire droite étage 1', 1, 'couloir', NULL, 'couloirSeconD_E1.jpg'),
	(163, 'couloir secondaire étage 2', 2, 'couloir', NULL, NULL);

-- Listage de la structure de table sorienter. tbl_user
CREATE TABLE IF NOT EXISTS `tbl_user` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL DEFAULT '0',
  `password` varchar(50) NOT NULL DEFAULT '0',
  `role` varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;

-- Listage des données de la table sorienter.tbl_user : ~0 rows (environ)

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
